apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Uses Docker internal DNS network
    isDefault: true
    editable: true # Allows you to still edit it via UI if needed for debugging
