vmanage_host: "192.168.0.50"
vmanage_username: "labuser"
vmanage_password: "Labpass01!"
sdwan_device_ip: "192.168.0.80"
target_image_version: "17.13.01a"
sdwan_username: "labuser"
sdwan_password: "Labpass01!"
ansible_network_os: ios
ansible_connection: network_cli
ansible_become_method: enable
ansible_user: "labuser"
ansible_ssh_pass: "Labpass01!"
ansible_become_password: "Labpass01!"
pre_check_commands_log : "PreCheckCommands.txt" 
post_check_commands_log : "PostCheckCommands.txt"
commands:
  # Add more commands as needed
  - "ter le 0"
  - "sh run"
  - "sh cdp nei"
  - "sh logg"
  - "sh ip int brief"
  - "sh int des"
  - "sh etherchannel summary"
  - "sh ip bgp summ"
  - "sh ip bgp"
  - "sh ip ospf nei"
  - "Sh dmvp"
  - "sh ip rou"
  - "sh ip arp"
  - "sh mac address"
  - "sh inv"
  #- "sh env all"
  - "sh power"
  - "sh platf"
  - "sh authentication sessio"
  - "sh lice all"
  - "sh lic udi"
  #- "sh lic right"
  - "sh run | i boot"
  - "sh ver"
  - "dir"
  - "sh flash:"
  #- "sh switch"
  - "sh ip bgp su"
  - "sh cdp nei"
  - "sh int desc"
  - "sh sdwan run"
  - "sh sdwan bfd session"
  - "sh sdwan control connections"
  - "sh sdwan system status"
  - "sh sdwan version"
  - "sh sdwan software"
