name: CI

on: [push, pull_request]

jobs:
  ci:
    uses: imsandeepreddy/workflows-template/.github/workflows/docker-ci.yaml@main
    secrets: inherit
    with:
      IMAGE_NAME: "node-hello"
