apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: myapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        
        # METHOD 1: Inject specific secret keys as Environment Variables
        env:
        - name: DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: DB_PASSWORD

        # METHOD 2: Mount the entire secret as secure files
        #volumeMounts:
        #- name: secret-volume
        #  mountPath: /app/secrets
        #  readOnly: true

      #volumes:
      #- name: secret-volume
      #  secret:
      #    secretName: myapp-secret
